### ISSUE TITLE
double return

### ISSUE THREAD

**Issue by nordfjord** [nicolashery/cjs-umd#4]
Hey, I'm trying out cjs-umd and loving it except for this one weird part.
When I bundle I get this

``` js
var _bundleExports = (function () {
    /* twelve thousand lines of code abbreviated */
    return return  _require(6);
}());
```

this means I have to manually edit one of those returns out for the bundle to work as expected,
any clues as to why this is happening?

With my regards,

Einar

**Comment by dlebedynskyi** [comment]
Had the same issue once.

**Comment by nicolashery** [comment]
Hi @nordfjord, I'm not sure why you are getting that double `return` statement.

You might want to take a look at [pure-cjs](https://github.com/RReverser/pure-cjs). This repository is actually a wrapper around it, because at the time it didn't support UMD, but it has now been added in `pure-cjs` via the `exports` option.

Sorry, I should have added a note in this repository. I just fixed that.

Hope it works out for you!
